baseURL = "https://haha077.github.io/blog/"
title = "blog"
theme = "ink"
languageCode = "zh-cn"
publishDir = "docs"

[pagination]
  pagerSize = 10

[params]
  subtitle = "haha's technical blog"
  author = "haha077"
  mode = "auto"  # 可选: light / dark / auto
  mainSections = ["posts", "blog"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[outputs]
home = ["HTML", "RSS", "JSON"]

  