baseURL = "https://haha077.github.io/blog/"
title = "Haha's Blog"
theme = "ink-free"
languageCode = "zh-cn"
publishDir = "docs"

[pagination]
  pagerSize = 10

[params]
  subtitle = "Haha's Technical Blog"
  author = "haha077"
  mode = "auto"  # 可选: light / dark / auto

[outputs]
  home = ["HTML", "JSON"]

  